(() => {
  const DIRECT = new Map([
    ['butter|||bts','WMweEpGlu_U'],['permission to dance|||bts','CuklIb9d3fI'],['dynamite|||bts','gdZLi9oWNZg'],['sunday morning|||maroon 5','S2Cti12XBw4'],['sugar|||maroon 5','09R8_2nJtjg'],['dandelion|||oohyo','Kaq4LFM47I0'],['comes and goes|||hyukoh','ECMc1SB60E0'],['love wins all|||iu','JleoAppaxi0'],['밤편지|||iu','BzYnNdJhZQw'],['through the night|||iu','BzYnNdJhZQw'],['love poem|||iu','iOKRYIMhaDk'],['attention|||newjeans','js1CtxSY38I'],['ditto|||newjeans','pSUydWEqKwE'],['perfect|||ed sheeran','2Vv-BfVoq4g'],['thinking out loud|||ed sheeran','lp-EO5I60KA'],['bad|||wave to earth','6Q5xqNkCk7w'],['seasons|||wave to earth','CnVVjLOGVoY'],['beautiful goodbye|||chen','JrOrlhjIYVk'],['untitled, 2014|||g-dragon','Nged3LwJsvQ'],['let her go|||passenger','RBumgq5yVrA'],['drivers license|||olivia rodrigo','ZmDBbnmKpqQ'],['기억을 걷는 시간|||nell','K72ZxP9ZAP4'],['space song|||beach house','RBtlPT23PTM'],["god's menu|||stray kids",'TQTlCHxyuu8'],['maniac|||stray kids','OvioeS1ZZ7o'],['believer|||imagine dragons','7wtfhZwyrcc'],['natural|||imagine dragons','0I647GU3Jsc'],['do i wanna know?|||arctic monkeys','bpOSxM0rNPM'],['seven nation army|||the white stripes','0J2QdDbelmY'],['golden hour|||jvke','PEM0Vs8jf1w'],['comethru|||jeremy zucker','jO2viLEW-1A'],['instagram|||dean','wKyMIrBClYw'],['d (half moon)|||dean','eelfrHtmk68'],['fix you|||coldplay','k4V3Mo61fJM'],['yellow|||coldplay','yKNxeF4KMsY'],['for lovers who hesitate|||jannabi','GpQ222I1ULc'],['apt.|||rosé & bruno mars','ekr2nIex040'],['uptown funk|||mark ronson feat. bruno mars','OPf0YbXqDm0'],["don't start now|||dua lipa",'oygrmJFKYZY'],['phonecert|||10cm','mOo8bVzN9M8'],['wave|||ateez','FIInyEWWW-s'],['ocean view|||rothy','5wiW60inhgw'],['ocean eyes|||billie eilish','viimfQi_pUw'],['ocean|||martin garrix feat. khalid','BDocp-VpCwY']
  ]);
  const emoji={행복:'😊',사랑:'💗',슬픔:'😢',화남:'😡',피곤:'😴',위로:'🥺',신남:'🤩',SHARK:'🦈'};
  const message={행복:'기분을 더 밝게 만들어줄 노래를 골라봤어.',사랑:'설레는 마음에 어울리는 노래를 골라봤어.',슬픔:'조용히 감정에 머물 수 있는 노래를 골라봤어.',화남:'답답한 기분을 시원하게 날려줄 노래를 골라봤어.',피곤:'힘을 빼고 편하게 들을 수 있는 노래를 골라봤어.',위로:'오늘 너에게 따뜻하게 닿을 노래를 골라봤어.',신남:'지금 에너지를 더 끌어올릴 노래를 골라봤어.',SHARK:'몽환적인 바다와 새벽 드라이브에 어울리는 노래를 골라봤어.'};
  const key=s=>`${String(s?.title||'').trim().toLowerCase()}|||${String(s?.artist||'').trim().toLowerCase()}`;
  const videoId=s=>String(s?.videoId||'').trim()||DIRECT.get(key(s))||'';
  const url=s=>{const id=videoId(s);return id?`https://music.youtube.com/watch?v=${encodeURIComponent(id)}`:''};
  const loadSaved=()=>{try{const v=JSON.parse(localStorage.getItem('sharkPlaylist')||'[]');return Array.isArray(v)?v:[]}catch{return[]}};
  const saveSaved=v=>localStorage.setItem('sharkPlaylist',JSON.stringify(v));
  const toggleSaved=s=>{let a=loadSaved();const k=key(s),i=a.findIndex(x=>key(x)===k);if(i>=0)a.splice(i,1);else a.push({title:s.title,artist:s.artist,videoId:videoId(s),url:url(s)});saveSaved(a);return a};
  const isSaved=s=>loadSaved().some(x=>key(x)===key(s));
  const open=s=>{const u=url(s);if(u) location.href=u};
  const shuffled=a=>{const r=[...a];for(let i=r.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[r[i],r[j]]=[r[j],r[i]]}return r};
  const loadObj=k=>{try{return JSON.parse(sessionStorage.getItem(k)||'{}')||{}}catch{return{}}};
  const five=(mood,genre)=>{const d=window.musicData?.[mood];if(!d)return[];let pool=genre==='ALL'?[...(d.KPOP||[]),...(d.POP||[]),...(d.INDIE||[])]:[...(d[genre]||[])];const seenKeys=new Set(),unique=[];for(const s of pool){const k=key(s);if(!seenKeys.has(k)&&videoId(s)){seenKeys.add(k);unique.push(s)}}pool=unique;if(!pool.length)return[];const H='sharkRecommendationHistoryDirectV4',L='sharkLastRecommendationsDirectV4',id=`${mood}_${genre}`,hist=loadObj(H),last=loadObj(L),seen=new Set(hist[id]||[]),need=Math.min(5,pool.length);let fresh=pool.filter(s=>!seen.has(key(s)));if(fresh.length<need){const lastSet=new Set(last[id]||[]),alt=pool.filter(s=>!lastSet.has(key(s)));fresh=alt.length>=need?alt:[...pool];seen.clear()}const selected=shuffled(fresh).slice(0,5);selected.forEach(s=>seen.add(key(s)));hist[id]=[...seen];last[id]=selected.map(key);sessionStorage.setItem(H,JSON.stringify(hist));sessionStorage.setItem(L,JSON.stringify(last));return selected};
  window.SHARK={emoji,message,key,videoId,url,loadSaved,saveSaved,toggleSaved,isSaved,open,five};
})();
